#arith.py
a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
#calculation print("_"*40)
print("{}+{}={}".format(a,b,a+b))
print("{}-{}={}".format(a,b,a-b))
print("{}*{}={}".format(a,b,a*b))
print("{}/{}={}".format(a,b,a/b))
print("{}//{}={}".format(a,b,a//b))
print("{}%{}={}".format(a,b,a%b))
print("{}**{}={}".format(a,b,a**b))
print("_"*50)