#relexpr.py
a=int(input("enter value of a:"))
b=int(input("enter value of b:"))
print("_"*40)
print("{}>{}={}".format(a,b,a>b))
print("{}>{}={}".format(a,b,b>a))
print("{}<{}={}".format(a,b,a<b))
print("{}<{}={}".format(a,b,b<a))
print("{}=={}={}".format(a,b,a==b))
print("{}!={}={}".format(a,b,a!=b))
print("{}>={}={}".format(a,b,a>=b))
print("{}>={}={}".format(a,b,b>=a))
print("{}<={}={}".format(a,b,a<=b))
print("{}<={}={}".format(a,b,b<=a))
print("_"*50)
